# PyTorch

In [1]:
import torch 

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [6]:
# Converting array to tensor- method 1 
x =torch .from_numpy(a) # creates alink between the numpy and the tensor, if you modify the cntent of numpy array then tensor also modified

In [7]:
type(x)

torch.Tensor

In [8]:
# method 2
torch.as_tensor(a)

tensor([1, 2, 3, 4, 5])

In [9]:
x.dtype

torch.int64

In [10]:
ar2d = np.arange(0.0,12.0).reshape(4,3)

In [11]:
ar2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
X2 = torch.from_numpy(ar2d)
X2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [16]:
#method 3
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
X3 = torch.tensor(arr)
X3

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# modifying original array to see the effect on tensor
X1 = torch.from_numpy(arr) # method 1
X2 =torch.as_tensor(arr) #method 2
X3 = torch.tensor(arr) #method 3

In [19]:
arr[0] =0 # modfiy the first element of orginal array
arr

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Checking the other arrays
X1 # modified

tensor([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
X2 # modified

tensor([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
X3 # not modified

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Tensor converts into floats- shorthand for FloatTensor
X4 = torch.Tensor(arr)
X4

tensor([0., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
# How to initialize tensor
torch.empty(2,2) # allocates a block of memory to later usuage for tensor

tensor([[1.3556e-19, 1.3563e-19],
        [4.6114e+24, 6.4600e+19]])

In [25]:
# To create a tensor of zeros of acertain dimension and data type
torch.zeros(4,2,dtype=torch.int32)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [26]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
# range start, end, step size
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [28]:
# linearly spcaed points
torch.linspace(0,8,12).reshape(3,4)

tensor([[0.0000, 0.7273, 1.4545, 2.1818],
        [2.9091, 3.6364, 4.3636, 5.0909],
        [5.8182, 6.5455, 7.2727, 8.0000]])

In [31]:
# change data type
X4.dtype

torch.float32

In [32]:
# convert float to int
X5 = X4.type(torch.int32)
X5.dtype

torch.int32

In [33]:
# random samples of tensor
torch.rand(4,3)

tensor([[0.6578, 0.6982, 0.0120],
        [0.3352, 0.6978, 0.9415],
        [0.3417, 0.8797, 0.7043],
        [0.3772, 0.0669, 0.6653]])

In [34]:
# normal distribution - mean = 0, std =1
torch.randn(4,3)

tensor([[-0.0100,  0.6359,  0.7163],
        [-0.9146,  0.8751, -1.6288],
        [-0.3421, -0.7345,  0.3887],
        [-0.4969, -0.6519,  1.2023]])

In [39]:
# random ints between a range, high is exclusive
torch.randint(low=0,high=10,size=(5,5))

tensor([[0, 5, 3, 3, 4],
        [9, 9, 3, 8, 2],
        [1, 0, 7, 7, 2],
        [2, 5, 6, 5, 6],
        [8, 8, 5, 2, 1]])

In [40]:
x=torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [42]:
# produces tensor of similar shape of x
torch.rand_like(x)

tensor([[0.5042, 0.8077, 0.2942, 0.7162, 0.2425],
        [0.0183, 0.4715, 0.4804, 0.8408, 0.2989]])

In [43]:
torch.randn_like(x)

tensor([[ 0.7215, -2.2367,  0.6815,  0.4720, -0.7795],
        [ 0.1171,  0.5575,  0.0050, -1.1097, -1.8734]])

In [44]:
# pass the size first and then low and high values
torch.randint_like(x,low=0, high=11)

tensor([[0., 6., 0., 2., 2.],
        [2., 0., 8., 7., 9.]])

In [45]:
# for reproducibility if you want same random values
torch.manual_seed(42)# it should be in the same cell with the rand to get the exact same output
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [47]:
# Tensor operrations
x= torch.arange(6).reshape(3,2)

In [50]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [49]:
x[1,1]

tensor(3)

In [52]:
# indexing for a column
x[:,1]

tensor([1, 3, 5])

In [53]:
#slicing the column
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [55]:
x= torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x.view(2,5) # just viewed in a particular shape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [57]:
x


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# to cahnge the tensor in place, ressign
x= x.reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [61]:
z= torch.arange(10).view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [62]:
z.shape

torch.Size([2, 5])

In [63]:
# After reassigning uisng view , the new tensor is linked to the orginal one and any modification in original will afect the new one
y = torch.arange(12)
y


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
z = y.view(4,3)
z

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [66]:
# change element in y 
y[1]= 99999
y

tensor([    0, 99999,     2,     3,     4,     5,     6,     7,     8,     9,
           10,    11])

In [67]:
# check z
z # it is alos modified 

tensor([[    0, 99999,     2],
        [    3,     4,     5],
        [    6,     7,     8],
        [    9,    10,    11]])

In [68]:
r = y.reshape(4,3)
r

tensor([[    0, 99999,     2],
        [    3,     4,     5],
        [    6,     7,     8],
        [    9,    10,    11]])

In [69]:
# modify y
y[10] = 8888
y

tensor([    0, 99999,     2,     3,     4,     5,     6,     7,     8,     9,
         8888,    11])

In [70]:
r # r is also modified, this is important for neural networking study

tensor([[    0, 99999,     2],
        [    3,     4,     5],
        [    6,     7,     8],
        [    9,  8888,    11]])

In [71]:
# Infer what the other dimension should be 
g = y.view(2,-1)
g # it automatically inferred that the other dimensin should be 6 if the row is given to be 2

tensor([[    0, 99999,     2,     3,     4,     5],
        [    6,     7,     8,     9,  8888,    11]])

In [72]:
h = y.view(-1,4)
h # similar ineference for columns

tensor([[    0, 99999,     2,     3],
        [    4,     5,     6,     7],
        [    8,     9,  8888,    11]])

In [73]:
# basic arithmatics with tensors
a = torch.tensor ([1.,2.,3.])
b = torch.tensor ([4.,5.,6.])

In [74]:
a

tensor([1., 2., 3.])

In [75]:
b

tensor([4., 5., 6.])

In [76]:
a+b # elementwise addition

tensor([5., 7., 9.])

In [77]:
torch.add(a,b)

tensor([5., 7., 9.])

In [79]:
# change the tensor in place by placing a unerscore 
a.add_(b) # a= a+b

tensor([5., 7., 9.])

In [80]:
# orginal value of a is now changed
a

tensor([5., 7., 9.])

In [81]:
b.mul_(a) # b= b*a

tensor([20., 35., 54.])

In [85]:
# dot product
c =a.dot(b)
c

tensor(32.)

In [89]:
a = torch.tensor ([[1.,2.,3.],[6.,7.,8.]])
b = torch.tensor ([[4.,5.],[3.,6.],[9.,10.]])

In [91]:
a.shape

torch.Size([2, 3])

In [93]:
b.shape

torch.Size([3, 2])

In [90]:
# Matrix multiplications no or rows of tensor 1 must match with number of column of tensor b
torch.mm(a,b)


tensor([[ 37.,  47.],
        [117., 152.]])

In [94]:
a@b # anaother way to do matrix multiplication

tensor([[ 37.,  47.],
        [117., 152.]])

In [95]:
# elucidian norm
x =torch.tensor([2.,3.,4.,5.5])

In [96]:
x.norm()

tensor(7.6974)

In [97]:
# no of elements in the tensor 
x.numel()

4

In [99]:
len(x)

4

In [100]:
# doing len on a 2d array will give number of rows
len(a)

2

In [101]:
# numel gives the number of elements
a.numel()

6

## Artificial Neural Network

In [105]:
# Pytorch gradients - Autogradients
x = torch.tensor(2.0,requires_grad =True) # requires_grad keeps track the computational history, can turn it off also

In [108]:
y = 2*x**4+x**3+3*x**2 + 5*x +1

In [109]:
y


tensor(63., grad_fn=<AddBackward0>)

In [110]:
# backpropagation in one step 
y.backward()

In [111]:
x.grad

tensor(93.)

In [129]:
# Backpropagation on multi layer 
# layer 1 = I/P is x, a 2x3 tensor
x = torch.tensor([[4.,5,6],[7,8,9]], requires_grad = True)
x

tensor([[4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [130]:
# layer 2 is y 
y = 3*x + 2
y

tensor([[14., 17., 20.],
        [23., 26., 29.]], grad_fn=<AddBackward0>)

In [131]:
# layer 3 is z
z = 2 * y**2
z

tensor([[ 392.,  578.,  800.],
        [1058., 1352., 1682.]], grad_fn=<MulBackward0>)

In [132]:
# layer 4 is o/p labelled as o = mean of z
o = z.mean()
o

tensor(977., grad_fn=<MeanBackward0>)

In [133]:
# backpropagation of o wrt x
o.backward()
x.grad

tensor([[28.0000, 34.0000, 40.0000],
        [46.0000, 52.0000, 58.0000]])

In [ ]:
# Linear reg with PyTorch

